### PR TITLE
Fix dotnet sdk resolution

### LINKED ISSUE #453: slngen failing when running on Windows Server 2022 and Linux intermittently
_Follow on from https://github.com/dotnet/sdk/issues/30361_

I'm not sure why we keep hitting this or what specifically triggers it, as it doesn't happen 100% of the time, but it does seem specific to extra sub-process spawning of `dotnet` that slngen itself does that causes our build to fail due to not resolving the SDK properly.

Logs from our CI process for linux and windows:

[corehost-logs.zip](https://github.com/microsoft/slngen/files/10711008/corehost-logs.zip)
[corehost-linux-logs.zip](https://github.com/microsoft/slngen/files/10711009/corehost-linux-logs.zip)

We can see from the logs the standard `dotnet` resolution from other tools and usage works fine, but the extra slngen one done adds extra info to the search path, this is clear on Windows where it's the actual executable embedded in the path:

>--- Resolving SDK information from global.json [D:\a\Labs-Windows\Labs-Windows\global.json]
>Value 'sdk/allowPrerelease' is missing or null in [D:\a\Labs-Windows\Labs-Windows\global.json]
>Resolving SDKs with version = '6.0.405', rollForward = 'latestFeature', allowPrerelease = true
>Searching for SDK versions in [C:\Program Files\dotnet\\**dotnet.exe**\sdk]
>A compatible .NET SDK was not found.

Following the linked source from @jeffkl's comments in the original issue, we can see as he mentioned that the dotnet executable is searched for here:
https://github.com/microsoft/slngen/blob/b19739dfbccbaf24b5d4c51b562f08b45e70a634/src/Shared/DevelopmentEnvironment.cs#L123

https://github.com/microsoft/slngen/blob/b19739dfbccbaf24b5d4c51b562f08b45e70a634/src/Shared/DevelopmentEnvironment.cs#L128

However, here that filename is being passed into the directory argument here, it should probably just be the **`dotnetFileInfo.DirectoryName`** value of the `FileInfo` object instead?
https://github.com/microsoft/slngen/blob/b19739dfbccbaf24b5d4c51b562f08b45e70a634/src/Shared/DotNetCoreSdkResolver.cs#L122

https://github.com/microsoft/slngen/blob/b19739dfbccbaf24b5d4c51b562f08b45e70a634/src/Shared/DotNetCoreSdkResolver.cs#L129

As then this is passed directly as the `directory` argument to the PInvokes to `hostfxr_resolve_sdk2` here:

https://github.com/microsoft/slngen/blob/b19739dfbccbaf24b5d4c51b562f08b45e70a634/src/Shared/DotNetCoreSdkResolver.cs#L148-L155

### PR DESCRIPTION
**Pull request by michael-hawker**
Fixes #453 

The initial fix for 453 only resolved passing the path which allowed it to find the proper location for the SDKs.

However, the actual outcome from the result of calling `hostfxr_resolve_sdk2` was ignored and not passed back to the calling function to use with the tool.

The error message was also returned as an empty string and thus was not showing up as the root cause either.

I validated with a private package in our CI that:
1) By returning an error message string this was indeed the path being taken on both our Linux and Windows servers
2) That the following patch allows them to get through this code path properly.

I also linked to the .NET repo which contains the native method's documentation as it does things like calls out the CharSet difference, the behavior of the return, and the values for the callback.

Wasn't sure if there was logging available here, could be a good thing for the future, as you can get the resolved version if `global.json` was used and print that out to the console.

Could also be good to add smoke tests which use the nuget package to install and run the tool in a scenario in your CI vs. just running the unit tests against the solution file scenarios?

### CODE REVIEW

File: src/Shared/DotNetCoreSdkResolver.cs [hunk 1]
```diff
@@ -25,17 +25,15 @@ public static class DotNetCoreSdkResolver
         /// </summary>
         /// <param name="environmentProvider">An <see cref="IEnvironmentProvider" /> to use when accessing the environment.</param>
         /// <param name="dotnetFileInfo">A <see cref="FileInfo" /> representing the path to dotnet.exe.</param>
-        /// <param name="basePath">Receives the root path of the .NET Core SDK if one is found.</param>
+        /// <param name="developmentEnvironment">Receives a <see cref="DevelopmentEnvironment" /> instance containing details of the .NET Core SDK if one is found.</param>
         /// <returns><code>true</code> if a .NET Core SDK could be located, otherwise <code>false</code>.</returns>
-        public static bool TryResolveDotNetCoreSdk(IEnvironmentProvider environmentProvider, FileInfo dotnetFileInfo, out DirectoryInfo basePath)
+        public static bool TryResolveDotNetCoreSdk(IEnvironmentProvider environmentProvider, FileInfo dotnetFileInfo, out DevelopmentEnvironment developmentEnvironment)
```
Comment (michael-hawker) [inline src/Shared/DotNetCoreSdkResolver.cs:30]: This tightly couples this helper class to your metadata class now.

File: src/Shared/DotNetCoreSdkResolver.cs [hunk 2]
```diff
@@ -78,11 +76,15 @@ public static bool TryResolveDotNetCoreSdk(IEnvironmentProvider environmentProvi
             {
                 if (!process.Start())
                 {
+                    developmentEnvironment = new DevelopmentEnvironment("Failed to resolve the .NET SDK.  Verify the 'dotnet' command is available on the PATH.");
```
Comment (michael-hawker) [inline src/Shared/DotNetCoreSdkResolver.cs:79]: Seem to be overloading the usage of `DevelopmentEnvironment` to just return different error messages?

**Review by michael-hawker — COMMENTED** [review]
Post-commit comments
